# Generated by Django 3.1.3 on 2021-06-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20210623_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='votes',
        ),
        migrations.AddField(
            model_name='choices',
            name='votes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
