# Generated by Django 3.1.3 on 2021-06-23 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20210623_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='votes',
        ),
        migrations.AddField(
            model_name='choices',
            name='votes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
