# Generated by Django 3.2.4 on 2021-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20210623_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
