# Generated by Django 3.2.4 on 2021-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20210623_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.IntegerField(),
        ),
    ]
